### ISSUE TITLE
Mincer 1.2.5 broke $$ interpolation for scss files

### ISSUE THREAD

**Issue by nemothekid** [nodeca/mincer#199] opened 2015-06-10 15:40 UTC
With Mincer 1.2.5, $$ expression $$ no longer evaluates to anything in scss files.

`app.js`
```js
mincer.MacroProcessor.configure ([ ".js", ".scss", ".cjsx", ".coffee" ])
```

`static.css.scss`
```scss
background: linear-gradient(to bottom, rgba(0,0,0,1) 0%, rgba(0,0,0,0) 17%),
			url('$$ image("home.jpg") $$');	background-size: cover;
```

In Mincer 1.2.4 the url css property is properly expanded out, while in Mincer 1.2.5 it doesn't so anything.

**Comment by ixti** [comment] 2015-06-11 00:06
Can you please provide an example? I was unable to reproduce with `examples`:

``` diff
 examples/assets/stylesheets/{app.css.ejs => app.css.scss} | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/examples/assets/stylesheets/app.css.ejs b/examples/assets/stylesheets/app.css.scss
similarity index 69%
rename from examples/assets/stylesheets/app.css.ejs
rename to examples/assets/stylesheets/app.css.scss
index 129c5ed..b221d75 100644
--- a/examples/assets/stylesheets/app.css.ejs
+++ b/examples/assets/stylesheets/app.css.scss
@@ -3,7 +3,7 @@
  **/

 body {
-  background: url('<%= image_path('stripes.png') %>');
+  background: url('$$ image_path("stripes.png") $$');
   transition: transform 1s;
 }
```

**Comment by nemothekid** [comment] 2015-06-11 06:10
So the example worked - after some digging if you change MacroProcessor config to 
```js
mincer.MacroProcessor.configure ([ ".js", ".scss", ".cjsx", ".coffee" ])
```
it won't work.
```diff
diff --git a/examples/environment.js b/examples/environment.js
index 04fbd06..bdc44c5 100644
--- a/examples/environment.js
+++ b/examples/environment.js
@@ -112,8 +112,8 @@ if (process.env.NODE_ENV === 'production') {
 //
 
 
-Mincer.MacroProcessor.configure([ '.js', '.css' ]/*, true */);
-
+// Mincer.MacroProcessor.configure([ '.js', '.css' ]/*, true */);
+Mincer.MacroProcessor.configure ([ ".js", ".scss", ".cjsx", ".coffee" ])
 
 //
 // Mincer rebuilt assets on any dependency file change. But sometime result
```

Now I'm not sure what the right value should be (using .scss as the MacroProcessor configure worked for me up until 1.2.5), and I'm not sure what extensions need to be specified. If I had to guess though, if for whatever reason I was serving straight up scss, then the I think the $$ interpolation wouldn't work?

**Comment by ixti** [comment] 2015-06-11 16:33
Tried different variants - neither reproduced bug:

``` javascript
Mincer.MacroProcessor.configure ([ ".js", ".css", ".scss" ])
Mincer.MacroProcessor.configure ([ ".js", ".css", ".scss", ".cjsx", ".coffee" ])
Mincer.MacroProcessor.configure ([ ".js", ".scss", ".cjsx", ".coffee" ])
```

**Comment by ixti** [comment] 2015-06-11 16:34
node-sass version I tried with:

``` javascript
{
  "name": "node-sass",
  "version": "3.1.2",
  "libsass": "3.2.4",
}
```

**Comment by puzrin** [comment] 2015-06-11 16:35
@nemothekid , please create a separate repo with example.

**Comment by nemothekid** [comment] 2015-06-11 16:41
@ixti That explains it, I was going to list our dependencies, but I checked `node-sass` first - ours is at ` "node-sass": "~0.9.3",` and upgrading to `3.1.2` solves the issue.

**Comment by puzrin** [comment] 2015-06-11 16:43
closing?

**Closed** 2015-06-11 16:43 UTC

**Comment by eruanntion** [comment] 2015-12-07 00:03
The same problem here. Macros work just fine in .js files, but not in .scss files. I'm using mincer 1.4 , node-sass 3.4.2. and connect-asset 5.0.1

**Comment by puzrin** [comment] 2015-12-07 03:59
@eruanntion please, create a repo with example, or PR new test, then open a new issue.
